### ISSUE TITLE
修改为--type miniprogram后，项目直接报错

### ISSUE THREAD

**Issue by jhxxs** [baranwang/tarojs-plugin-platform-miniprogram#1]
项目使用的是`taro`+`ts`+`react`

如果按照文档将npm script改为--type miniprogram后项目会报“全局配置缺少 pages 字段”，
如果不修改--type，项目正常运行，但从插件里引入的PageMeta不会编译

![image](https://user-images.githubusercontent.com/7448223/146130303-62439e19-dc39-4ce1-9188-44bc9b80c402.png)

**Comment by baranwang** [comment]
@jhxxs `app.config.ts`没有配置 pages 吗？

**Comment by jhxxs** [comment]
有配置pages但是是针对--type weapp的，请问为什么要将--type改为miniprogram?

**Comment by baranwang** [comment]
> 有配置pages但是是针对--type weapp的，请问为什么要将--type改为miniprogram?

因为 `weapp` 已由 `@tarojs/cli` 内置的 `@tarojs/plugin-platform-weapp` 注册（具体可以查看 [Taro 的相关文档](https://taro-docs.jd.com/taro/docs/implement-note#%E7%AB%AF%E5%B9%B3%E5%8F%B0%E6%8F%92%E4%BB%B6)），无法重复注册，所以只能换一个名字。

这个插件本事就是继承了 `@tarojs/plugin-platform-weapp` 做了构建后的一些处理而已。

**Comment by baranwang** [comment]
@jhxxs 如果已经配置 pages 还会出现这样的问题，可以提供一个可以重现的代码链接。我看下是什么问题

**Comment by jhxxs** [comment]
👍🏻目前可用了，但因为修改taro env导致项目本身需要一些改动。

**Comment by baranwang** [comment]
不知道对于 taro 对于继承插件共用平台名有什么更优雅的解决方案没有，目前只能这样了。
