### ISSUE TITLE
PageMeta,NavigationBar引入不生效

### ISSUE THREAD

**Issue by zhilianbi520** [baranwang/tarojs-plugin-platform-miniprogram#4]
```
import { Component } from 'react'
import {connect} from "react-redux";
import Taro from "@tarojs/taro";
import { PageMeta, NavigationBar } from "tarojs-plugin-platform-miniprogram/dist/components";

import "taro-ui/dist/style/components/button.scss" // 按需引入
import './index.scss'

@connect(({index})=>({
    index
}))
export default class Index extends Component {
    constructor (props) {
        super(props)
        this.state = {
            name:'',
        }
    }
  componentWillMount () {
// 以下方法无法正常运行
      Taro.getCurrentInstance().page.setData({
          pageMeta:{
               backgroundTextStyle:'dark',
          },
          navigationBar:{
             title:'xxx'
         }
      })
        console.info(Taro.getCurrentInstance().page);
  }
  render () {
    return (
        <>
            <PageMeta>
                <NavigationBar title='Awesome Taro' />
                xxxx
            </PageMeta>
        </>
    )
  }
}
```
![20220114154004](https://user-images.githubusercontent.com/16549630/149469732-011c8538-50d3-48e2-9c82-f122e708b8ac.jpg)
taro版本：3.4.0
插件版本：0.1.1

**Comment by baranwang** [comment]
React 版本小于 16.8 ？

**Comment by baranwang** [comment]
React 版本小于 16.8 ？

**Comment by zhilianbi520** [comment]
@baranwang react的版本是17

**Comment by zhilianbi520** [comment]
> React 版本小于 16.8 ？

@baranwang react的版本是17，刚搭建的项目。

**Comment by baranwang** [comment]
~可以提供一个用例吗？我这边看一下~

好像 React Hook API 的组件不能用在 class API 的组件内，所以可以尝试自己重新封装一个基于 class API 的组件，或者页面改用 Hook API 书写

**Comment by zhilianbi520** [comment]
> ~可以提供一个用例吗？我这边看一下~
> 
> 好像 React Hook API 的组件不能用在 class API 的组件内，所以可以尝试自己重新封装一个基于 class API 的组件，或者页面改用 Hook API 书写

好咧。或者降级react16.8+也可解决？

**Comment by zhilianbi520** [comment]
> ~可以提供一个用例吗？我这边看一下~
> 
> 好像 React Hook API 的组件不能用在 class API 的组件内，所以可以尝试自己重新封装一个基于 class API 的组件，或者页面改用 Hook API 书写

好的，我试试的。

**Comment by zhilianbi520** [comment]
> ~可以提供一个用例吗？我这边看一下~
> 
> 好像 React Hook API 的组件不能用在 class API 的组件内，所以可以尝试自己重新封装一个基于 class API 的组件，或者页面改用 Hook API 书写

修改为 Hook API 书写后，连基本的demo结构都不展示了。

**Comment by zhilianbi520** [comment]
> ~可以提供一个用例吗？我这边看一下~
> 
> 好像 React Hook API 的组件不能用在 class API 的组件内，所以可以尝试自己重新封装一个基于 class API 的组件，或者页面改用 Hook API 书写

```
import React, { FC, useState, useEffect } from "react";
import {connect} from "react-redux";
import { PageMeta, NavigationBar } from "tarojs-plugin-platform-miniprogram/dist/components";
import "taro-ui/dist/style/components/button.scss" // 按需引入
import './index.scss'



const Index:FC = (props:any) =>{
    return (
        <>
            <PageMeta>
                <NavigationBar title='Awesome Taro' />
                xxx
            </PageMeta>
        </>
    )
}
export default connect(({ index }: any) => ({
    index
}))(Index)
```
已修改为以上写法，效果相同。

**Comment by baranwang** [comment]
Hook API 的 redux 应该不是这样写的吧 https://react-redux.js.org/api/hooks

**Comment by zhilianbi520** [comment]
> Hook API 的 redux 应该不是这样写的吧 https://react-redux.js.org/api/hooks
跟这个无关吧，那个的配置是数据的配置，会影响到组件引入么？没影响吧。

**Comment by baranwang** [comment]
给我一个你最小化的代码的仓库吧 我帮你看一下

**Comment by zhilianbi520** [comment]
> 给我一个你最小化的代码的仓库吧 我帮你看一下
https://github.com/zhilianbi520/tarodemo.git 这是相关的代码，麻烦了，多谢～！

**Comment by baranwang** [comment]
运行你的代码没有问题啊

**Comment by zhilianbi520** [comment]
> 运行你的代码没有问题啊

哈？我本地跑起来的。还是上面那个现象。。头部没高度没内容的。方便截图下你运行的情况么？依赖包我删了重新打也还是那样的。

**Comment by baranwang** [comment]
真机上看一下呢？我在模拟器上也是看不到，但是看到数据有变化

**Comment by zhilianbi520** [comment]
> 



> 真机上看一下呢？我在模拟器上也是看不到，但是看到数据有变化

还真是，模拟器上真的就没有，多谢～！

**Comment by zhilianbi520** [comment]
模拟器上暂时还是展示不粗来，但是真机测试无该问题，所以关闭该提问，多谢作者解答。
